name: soft_edge_blur
description: "A customizable Flutter widget that applies a soft blur effect to one or more edges of its child widget."
version: 0.0.2
repository: https://github.com/Rahiche/soft_edge_blur

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


