name: Flutter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test --update-goldens

      - name: Run Widget Tests
        run: flutter test test/soft_edge_blur_test.dart
